env:
    es6: true
    node: true
    mocha: true
extends: 'eslint:recommended'
settings:
    import/resolver: webpack
parserOptions:
    ecmaVersion: 7
    sourceType: module
parser: "babel-eslint"
rules:
    strict: 0
    indent:
        - warn
        - 2
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    no-unused-vars: 0
    no-console: 0
    comma-dangle: 
        - 0
        - always-multiline
    no-trailing-spaces:
        - error
    no-debugger: 0
